SELECT FIRST_NAME,
LOWER(FIRST_NAME)
FROM EMPLOYEES;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) = 'david';

SELECT UPPER('PRIVET'||' kak dela?'||' skolko let?') FROM DUAL;

SELECT FIRST_NAME,
INITCAP('It''s name '||first_Name|| ' beutiful name')AS NAME
FROM EMPLOYEES; 

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE '%en';

SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME)=5;

SELECT COUNTRY_NAME
FROM COUNTRIES
WHERE LENGTH(COUNTRY_NAME)>5;

SELECT EMAIL,
SUBSTR(EMAIL,4)
FROM EMPLOYEES;

SELECT SUBSTR('PRIVET KAK DELA',3,3) FROM DUAL;

SELECT REPLACE('PRIVET KAK DELA','E','%') FROM DUAL;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '17.08.02' AND '30.01.05'
ORDER BY HIRE_DATE;

SELECT EMPLOYEE_ID,
MONTHS_BETWEEN(END_DATE,START_DATE) 
FROM JOB_HISTORY;







