SELECT * FROM REGIONS
NATURAL JOIN COUNTRIES
WHERE REGION_NAME = 'Europe';


SELECT * FROM EMPLOYEES
NATURAL JOIN JOB_HISTORY;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT  FIRST_NAME,DEPARTMENT_ID, MANAGER_ID,DEPARTMENT_NAME FROM EMPLOYEES e
JOIN DEPARTMENTS d
USING(DEPARTMENT_ID,MANAGER_ID)
ORDER BY 1 ASC;

SELECT * FROM EMPLOYEES e
JOIN JOB_HISTORY j
ON(E.EMPLOYEE_ID = j.EMPLOYEE_ID);

