SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
    SET
SALARY = 24000
WHERE EMPLOYEE_ID =100;

UPDATE EMPLOYEES
    SET
SALARY = 15000
WHERE EMPLOYEE_ID <106;

SELECT * FROM DEPARTMENTS;

UPDATE EMPLOYEES
    SET
SALARY = 5000
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS  WHERE DEPARTMENT_NAME = 'Marketing');

UPDATE EMPLOYEES
    SET
SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES)
WHERE EMPLOYEE_ID = 100;

SELECT * FROM COUNTRIES;

INSERT INTO COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID)
VALUES('SP','SPANIA',1);

DELETE FROM COUNTRIES
WHERE COUNTRY_NAME = 'SPANIA';

SELECT * FROM DEPARTMENTS;

