SELECT FIRST_NAME,LAST_NAME,EMAIL,SALARY,START_DATE,END_DATE
FROM EMPLOYEES e
JOIN JOB_HISTORY jh
ON(E.EMPLOYEE_ID = jh.EMPLOYEE_ID And e.DEPARTMENT_ID=JH.DEPARTMENT_ID);

SELECT * FROM JOB_HISTORY;
SELECT * FROM EMPLOYEES;

SELECT emp1.EMPLOYEE_ID,emp1.First_name,emp1.Manager_id, emp2.First_name AS maneger_name
FROM EMPLOYEES emp1
JOIN EMPLOYEES emp2
ON(emp1.MANAGER_ID=EMP2.EMPLOYEE_ID);

SELECT * FROM EMPLOYEES E
RIGHT OUTER JOIN  DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES E
LEFT OUTER JOIN  DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);