SELECT FIRST_NAME,SALARY,HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%A%'
    UNION ALL 
SELECT FIRST_NAME,SALARY,HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%A%'; 

SELECT FIRST_NAME,SALARY,EMAIL FROM EMPLOYEES
WHERE EMAIL LIKE '%M%'AND SALARY  BETWEEN 5000 AND 9000
    UNION
SELECT FIRST_NAME,SALARY,EMAIL FROM EMPLOYEES
WHERE EMAIL LIKE '%M%' AND SALARY  BETWEEN 5000 AND 9000;