SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = 10000;

SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY !=10000;

SELECT * FROM EMPLOYEES
WHERE LAST_NAME > 'Steven';

SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN EMPLOYEE_ID AND 10000;

SELECT * FROM DEPARTMENTS
WHERE LOCATION_ID IN (1700,1500,2400);

SELECT * FROM JOB_HISTORY
WHERE JOB_ID IN ('IT_PROG');