SELECT * FROM REGIONS;

SELECT FIRST_NAME, DEPARTMENT_ID,SALARY,LAST_NAME 
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, EMAIL,HIRE_DATE,HIRE_DATE-7 as "One week before hire date"
FROM EMPLOYEES;

SELECT FIRST_NAME || '(' || JOB_ID || ')' as our_employees
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME
FROM EMPLOYEES;

SELECT JOB_TITLE,'MIN='|| MIN_SALARY || ', MAX=' || MAX_SALARY AS INFO,MAX_SALARY AS MAX,
(MAX_SALARY*2)-2000 AS "NEW SALARY"
FROM JOBS;

SELECT q'<Peter's dog is very clever>'
FROM DUAL;

SELECT 'Peter''s dog is very clever' 
FROM DUAL;

SELECT 100*365.25*24*60
FROM DUAL