SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME ='David';

SELECT FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID ='FI_ACCOUNT';

SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50 and SALARY>4000;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID =30;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a%a';

SELECT * FROM EMPLOYEES
WHERE  (DEPARTMENT_ID =50 or DEPARTMENT_ID =80) and COMMISSION_PCT IS NOT null
ORDER BY EMAIL;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n%n%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%_____%'
ORDER BY DEPARTMENT_ID DESC NULLS LAST;

SELECT * FROM EMPLOYEES
WHERE (SALARY BETWEEN 3000 AND 7000) AND COMMISSION_PCT IS NULL AND JOB_ID IN('PU_CLERK','ST_MAN','ST_CLERK');

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%\%%' ESCAPE '\';

SELECT JOB_ID,FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID >=120 AND JOB_ID !='IT_PROG'
ORDER BY JOB_ID,FIRST_NAME DESC;

