SELECT * FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) =(SELECT MAX(LENGTH(FIRST_NAME)) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT CITY,SUM(SALARY) FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
    JOIN LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
GROUP BY CITY
HAVING SUM(SALARY) = (SELECT MIN(SUM(SALARY)) FROM EMPLOYEES E
                     JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
                     JOIN LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
                    GROUP BY CITY);

SELECT * FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES
                    WHERE SALARY >15000);

SELECT * FROM 
(SELECT * FROM EMPLOYEES E
 RIGHT OUTER  JOIN DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE FIRST_NAME IS NULL);

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN  (SELECT DISTINCT MANAGER_ID FROM EMPLOYEES
                       WHERE MANAGER_ID IS NOT NULL);
                       
SELECT *FROM EMPLOYEES E
WHERE (SELECT COUNT(*) FROM EMPLOYEES 
       WHERE MANAGER_ID = E.EMPLOYEE_ID)>6;

SELECT * FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
 WHERE DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME FROM EMPLOYEES
                            WHERE UPPER(DEPARTMENT_NAME) LIKE 'IT');

SELECT * FROM EMPLOYEES 
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES
                    WHERE TO_CHAR(HIRE_DATE,'YYYY')='2005') AND HIRE_DATE<TO_DATE('01012005','DDMMYYYY');
                    
SELECT * FROM EMPLOYEES E
JOIN JOBS J ON(E.JOB_ID = J.JOB_ID)
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES
                     WHERE TO_CHAR(HIRE_DATE,'MON') = 'JUN') AND JOB_TITLE IN (SELECT (JOB_TITLE) FROM JOBS
                                                                  WHERE LENGTH(JOB_TITLE)>15);