SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%B%';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%A%A%';

SELECT FIRST_NAME, SUBSTR(FIRST_NAME,2,(LENGTH(FIRST_NAME)-2))
FROM EMPLOYEES;

SELECT JOB_ID, SUBSTR(JOB_ID,(INSTR(JOB_ID,'_')))
FROM EMPLOYEES
WHERE LENGTH(SUBSTR(JOB_ID,(INSTR(JOB_ID,'_'))))>3 AND SUBSTR(JOB_ID,(INSTR(JOB_ID,'CLERK')))!='CLERK';

SELECT *  FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'DD')='01';

SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')= '2008';

SELECT TO_CHAR(SYSDATE+1,'"Tomorrow is" DAY "day of" MONTH') FROM DUAL;

SELECT FIRST_NAME, TO_CHAR(HIRE_DATE,'DDth "of" FMMONTH,YYYY') FROM EMPLOYEES;

SELECT SALARY, TO_CHAR((SALARY*0.2+SALARY),'$99,999.99') FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY,SALARY+ TO_NUMBER('$12,345.55','$99,999.99') AS NEW_SALARY
FROM EMPLOYEES;
    
SELECT FIRST_NAME,HIRE_DATE,MONTHS_BETWEEN(TO_DATE('SEP, 18:45:00 18 2009','MON, HH24:MI:SS DD YYYY'),HIRE_DATE) AS NEW_DATE
FROM EMPLOYEES;

SELECT FIRST_NAME,COMMISSION_PCT,SALARY, TO_CHAR((SALARY+SALARY * NVL(commission_pct,0)),'$99,999.99') AS FULL_SALARY
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME,NVL2(NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)),'different length','same length')
FROM EMPLOYEES;

SELECT FIRST_NAME,COMMISSION_PCT,NVL2(COMMISSION_PCT,'YES','NO') AS INFO_COMMISSION_PCT
FROM EMPLOYEES;


SELECT FIRST_NAME,COALESCE(commission_pct,MANAGER_ID,SALARY)AS INFO
FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY,
CASE
WHEN SALARY <5000 THEN 'Low level'
WHEN SALARY >=5000 AND SALARY <10000 THEN 'Normal level'
WHEN SALARY >=10000 THEN 'High levell'
END AS INFO
FROM EMPLOYEES;

SELECT COUNTRY_NAME,DECODE(REGION_ID,1,'Europe',2,'America',3,'Asia',4,'Africa') AS INFO
FROM COUNTRIES;

SELECT COUNTRY_NAME,
CASE REGION_ID
WHEN 1 THEN 'Europe'
WHEN 2 THEN 'America'
WHEN 3 THEN 'Asia'
WHEN 4 THEN 'Africa'
END AS INFO
FROM COUNTRIES;

SELECT FIRST_NAME,SALARY,
CASE
WHEN SALARY<10000 AND COMMISSION_PCT IS NULL THEN 'BAD'
WHEN SALARY BETWEEN 10000 AND 15000 OR commission_pct IS NOT NULL THEN 'NORMAL'
WHEN SALARY >=15000 THEN 'GOOD'
END AS INFO
FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES;


 