CREATE TABLE EMP1000 AS
(SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES);

CREATE FORCE VIEW V1000 AS
(SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NAME,EMP1000.CITY FROM EMP1000
JOIN DEPARTMENTS ON (EMP1000.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT.ID));

ALTER TABLE EMP1000 ADD (CITY VARCHAR2(30));

ALTER VIEW V1000 COMPILE;

CREATE SYNONYM SYN1000
FOR V1000;

DROP VIEW V1000;
DROP SYNONYM SYN1000;
DROP TABLE EMP1000;

CREATE SEQUENCE SEQ1000
INCREMENT BY  4
START WITH 12
MAXVALUE 200
CYCLE;

ALTER SEQUENCE SEQ1000
NOMAXVALUE
NOCYCLE;

INSERT INTO EMPLOYEES(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,HIRE_DATE,JOB_ID)
VALUES(SEQ1000.NEXTVAL,'IVAN','IVANOV','ANCAC','21-SEP-09','IT_PROG');

INSERT INTO EMPLOYEES(EMPLOYEE_ID,FIRST_NAME,LAST_NAME, EMAIL,HIRE_DATE,JOB_ID)
VALUES(SEQ1000.NEXTVAL,'SUSAN','VAER','DFGDFS','17-SEP-03','IT_PROG');
ROLLBACK;
SELECT *FROM EMPLOYEES




