CREATE TABLE friends(ID,NAME,SURNAME) AS
(SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);

SELECT * FROM FRIENDS;

DESCRIBE EMPLOYEES;

ALTER TABLE FRIENDS ADD(EMAIL VARCHAR2(25));

ALTER TABLE FRIENDS MODIFY( EMAIL VARCHAR2(25) DEFAULT 'no Email');

INSERT INTO FRIENDS (ID,NAME,SURNAME)
VALUES(156,'MMM','RTR');

ALTER TABLE FRIENDS 
RENAME COLUMN ID TO FRIENDS_ID; 

DROP TABLE FRIENDS;

CREATE TABLE FRIENDS (ID NUMBER(6),NAME VARCHAR2(20),SURNAME VARCHAR2(25),EMAIL VARCHAR2(25),SALARY NUMBER(8,2)
DEFAULT 0, CITY VARCHAR(15),BIRTHDAY DATE DEFAULT TO_DATE('20-JUN-2001','DD-MON-YYYY'));

INSERT INTO FRIENDS (ID,NAME,SURNAME,EMAIL,SALARY,CITY,BIRTHDAY)
VALUES(1,'IVAN','IVANOV','IVANo',5000,'ITALIA','15-JUL-2003');

UPDATE FRIENDS 
    SET
EMAIL = 'IAVANo@gmail.com'
WHERE ID =1;

INSERT INTO FRIENDS(ID,NAME,SURNAME,EMAIL)
VALUES(2,'STEPAN','KURPATOV','Kurpatov@gmail.com');
COMMIT;

ALTER TABLE FRIENDS DROP COLUMN SALARY;

ALTER TABLE FRIENDS SET UNUSED COLUMN EMAIL;

ALTER TABLE FRIENDS SET UNUSED COLUMN BIRTHDAY;

ALTER TABLE FRIENDS DROP UNUSED COLUMNS;

ALTER TABLE FRIENDS READ ONLY;

UPDATE FRIENDS
    SET 
ID = 1;

TRUNCATE TABLE FRIENDS;

DROP TABLE FRIENDS;

