SELECT REGION_NAME,COUNT(*)
FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
    JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
    JOIN COUNTRIES C ON (L.COUNTRY_ID=C.COUNTRY_ID)
    JOIN REGIONS R ON (C.REGION_ID = R.REGION_ID)
GROUP BY REGION_NAME; 

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,JOB_ID,STREET_ADDRESS,COUNTRY_NAME,REGION_NAME
FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
    JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
    JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
    JOIN REGIONS R ON(C.REGION_ID = R.REGION_ID);
    
SELECT EMP2.FIRST_NAME,COUNT(*)
FROM EMPLOYEES EMP1
    JOIN EMPLOYEES EMP2
    ON(EMP1.MANAGER_ID=EMP2.EMPLOYEE_ID)
    GROUP BY EMP2.FIRST_NAME
    HAVING COUNT(*)>6;

SELECT DEPARTMENT_NAME,COUNT(*) AS NUMBER_OF_EMPLOYEES
FROM EMPLOYEES
    JOIN DEPARTMENTS
    USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*)>30;

SELECT DEPARTMENT_NAME
FROM EMPLOYEES E
  RIGHT OUTER JOIN DEPARTMENTS D
  ON(E.DEPARTMENT_ID =D.DEPARTMENT_ID)
WHERE E.DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES EMP1
    JOIN EMPLOYEES EMP2
ON(EMP1.MANAGER_ID = EMP2.EMPLOYEE_ID)
WHERE TO_CHAR(EMP2.HIRE_DATE,'YYYY') =2005 AND TO_CHAR(EMP1.HIRE_DATE,'YYYY')<2005;

SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES
NATURAL JOIN REGIONS;

SELECT FIRST_NAME,LAST_NAME,SALARY,MIN_SALARY
FROM EMPLOYEES E
    JOIN JOBS J ON(E.JOB_ID = J.JOB_ID AND SALARY<MIN_SALARY+1000);
    
SELECT DISTINCT FIRST_NAME,LAST_NAME,COUNTRY_NAME
FROM EMPLOYEES E
    FULL OUTER  JOIN DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
    FULL OUTER  JOIN LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
    FULL OUTER  JOIN COUNTRIES C ON(L.COUNTRY_ID = C.COUNTRY_ID);

SELECT FIRST_NAME,LAST_NAME,COUNTRY_NAME
FROM EMPLOYEES
CROSS JOIN COUNTRIES;

SELECT REGION_NAME,COUNT(*) FROM EMPLOYEES E,DEPARTMENTS D,LOCATIONS L,COUNTRIES C, REGIONS R
WHERE  E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID=C.COUNTRY_ID AND C.REGION_ID = R.REGION_ID
GROUP BY REGION_NAME;

SELECT DEPARTMENT_NAME FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID (+)= D.DEPARTMENT_ID AND E.DEPARTMENT_ID IS NULL;

   

 


    
   

    
    