CREATE TABLE LOCATIONS2 AS (SELECT * FROM LOCATIONS WHERE 1 =2);

SELECT * FROM LOCATIONS2;
SELECT * FROM LOCATIONS;
SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;

INSERT INTO  LOCATIONS2 (LOCATION_ID,STREET_ADDRESS, CITY,COUNTRY_ID)
 (SELECT LOCATION_ID,STREET_ADDRESS, CITY,COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID = 'IT');

COMMIT;

INSERT INTO LOCATIONS2 
VALUES (1300,INITCAP('1350 DE RUNAR'),null, INITCAP('parish'),null, UPPER('fr'));
INSERT INTO LOCATIONS2
VALUES(1500,INITCAP( '9690 DE PIRAMID'),null,INITCAP('PARISH'),null,UPPER('fr'));
COMMIT;

INSERT INTO LOCATIONS2 
(SELECT * FROM LOCATIONS WHERE LENGTH(STATE_PROVINCE) >9);
COMMIT;

CREATE TABLE locations4europe AS (SELECT * FROM locations WHERE 1=2);

INSERT ALL
WHEN 1 = 1 THEN INTO LOCATIONS2 VALUES (LOCATION_ID,STREET_ADDRESS,POSTAL_CODE,CITY,STATE_PROVINCE,COUNTRY_ID)

WHEN COUNTRY_ID IN (SELECT COUNTRY_ID FROM COUNTRIES WHERE REGION_ID IN (SELECT REGION_ID FROM REGIONS WHERE REGION_NAME ='Europe')) THEN 
INTO locations4europe (LOCATION_ID,STREET_ADDRESS, CITY,COUNTRY_ID) VALUES (LOCATION_ID,STREET_ADDRESS, CITY,COUNTRY_ID)

SELECT * FROM LOCATIONS;
COMMIT;

SELECT * FROM LOCATIONS2;

UPDATE LOCATIONS2
    SET
POSTAL_CODE = 13456
WHERE POSTAL_CODE IS NULL;
ROLLBACK;

UPDATE LOCATIONS2
    SET
POSTAL_CODE = (SELECT POSTAL_CODE FROM LOCATIONS WHERE LOCATION_ID = 2600)
WHERE POSTAL_CODE IS NULL;
COMMIT;

DELETE FROM LOCATIONS2
WHERE COUNTRY_ID = 'IT';
SAVEPOINT S1;

UPDATE LOCATIONS2
SET STREET_ADDRESS = 'Sezam st. 18'
WHERE LOCATION_ID >2500;
SAVEPOINT S2;

DELETE FROM LOCATIONS2
WHERE STREET_ADDRESS = 'Sezam st. 18';

ROLLBACK TO S1;
COMMIT;


 